### PR TITLE
explicitly fail non dictionary env section

### LINKED ISSUE #367: "Could not connect to Binaris backend" caused by YAML format errors
# The Problem
`binaris.yml` validation/format errors produce a generic `Could not connect to Binaris backend` message which is useless for debugging.

## Steps To Reproduce
I have deployed a function with a malformed `binaris.yml` `env` section, without a `:` suffix on the entries.

```
functions:
  handleTrelloEvent:
    file: handleTrelloEvent.js
    entrypoint: handler
    runtime: node8
  listWebhooks:
    file: listWebhooks.js
    entrypoint: handler
    runtime: node8
    env:
      TRELLO_API_KEY   <-----
      TRELLO_TOKEN     <-----
```

Upon deployment of the second function, the following error appeared:
```
Could not connect to Binaris backend
```

The first function, `handleTrelloEvent`, was deployed without any problems.

## Debug output
`BINARIS_LOG_LEVEL=debug` gives:

        ...
        toJSON: [Function: responseToJSON],
        caseless:
         Caseless {
           dict:
            { date: 'Sun, 04 Nov 2018 11:49:46 GMT',
              'content-type': 'application/json; charset=utf-8',
              'content-length': '279',
              connection: 'keep-alive',
              'x-powered-by': 'Express',
              etag: 'W/"117-t0rgb2tsf1KQoQsVnqAlEd1PD8E"' } },
        read: [Function],
        body:
         { errorCode: 'ERR_BAD_REQUEST',
           message: 'Invalid request parameters (see errors field)',
           errors:
            [ { keyword: 'type',
                dataPath: '.env',
                schemaPath: '#/properties/env/type',
                params: { type: 'object' },
                message: 'should be object' } ],
           debugId: 'be7df41c-7bba-4713-848b-9db852c52601' } } } }

# Expected Behaviour
Validation errors in `binaris.yml` should give explicit error messages with a clear indication to the location of the problem. If possible, these validations should be performed locally to reduce the duration of the debugging cycles.

### PR DESCRIPTION
**Pull request by michaeladda**
based on #406 (will rebase if needed)
fixes #367
tested with CI

### CODE REVIEW

File: sdk/deploy.js [hunk 1]
```diff
@@ -59,6 +59,9 @@ const deployCode = async function deployCode(accountId, apiKey, tarPath) {
 const deployConf = async function deployConf(accountId, funcName, apiKey, funcConf) {
   const { env } = funcConf;
   if (env) {
+    if (typeof env !== 'object') {
+      throw new Error('YAML env section must be a dictionary.');
```
Comment (arielshaqed) [inline sdk/deploy.js]: Can we log the filename instead of "`YAML`"?

File: sdk/deploy.js [hunk 2]
```diff
@@ -60,7 +60,7 @@ const deployConf = async function deployConf(accountId, funcName, apiKey, funcCo
   const { env } = funcConf;
   if (env) {
     if (typeof env !== 'object') {
-      throw new Error('YAML env section must be a dictionary.');
+      throw new Error('binaris.yml env section must be a dictionary.');
```
Comment (arielshaqed) [inline sdk/deploy.js]: Whew...  This is just barely correct, because `--path` lets us specify a directory but _not_ a different filename inside it.
Cool, thanks!
